# This is a basic workflow to help you get started with Actions

name: runGMDonCI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on ubuntu-latest
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@main

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Accept Android licenses
        run: yes | "$ANDROID_HOME"/cmdline-tools/latest/bin/sdkmanager --licenses || true
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      # Execute the clean managed devices to avoid lack of disk space for emulator snapshot
      - name: Execute Clean Managed Devices
        run: ./gradlew app:cleanManagedDevices --info
        
      # Execute Gradle managed device commands
      - name: GMD device1 setup
        run: ./gradlew app:device1Setup
